# These are supported funding model platforms

github: [karnwatcharasupat] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: kwatcharasupat # Replace with a single Ko-fi username
